---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install docker
  become: true
  remote_user: root
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
